# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(max_length=700)),
                ('codigo', models.TextField(max_length=700)),
                ('img_issue', models.ImageField(upload_to='pic_folder/')),
                ('slug', models.SlugField(max_length=31, unique=True)),
                ('colaboradores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_img', models.ImageField(upload_to='pic_folder/')),
                ('descripcion_code', models.TextField(max_length=700)),
                ('slug', models.SlugField(max_length=31, unique=True)),
                ('Colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Colaborador')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
                ('slug', models.SlugField(help_text='Una etiqueta para configuracion de la url.', max_length=31, unique=True)),
            ],
        ),
    ]
