# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='descripcion',
            field=models.TextField(blank=True, max_length=700),
        ),
    ]
