# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20170320_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha de publicación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha de publicación'),
            preserve_default=False,
        ),
    ]
