# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20170320_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='slug',
            field=models.SlugField(blank=True, max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='slug',
            field=models.SlugField(blank=True, max_length=31, unique=True),
        ),
    ]
