# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_pregunta_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='descripcion',
            field=models.TextField(default='Nothing', max_length=700),
            preserve_default=False,
        ),
    ]
