# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_respuesta_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='descripcion',
            field=models.TextField(max_length=700, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='descripcion_code',
            field=models.TextField(max_length=700, verbose_name='Mostrar código'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='descripcion_img',
            field=models.ImageField(upload_to='pic_folder/', verbose_name='Cargar imagen'),
        ),
    ]
