# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_auto_20170321_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='slug',
        ),
    ]
