# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_remove_respuesta_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='descripcion_img',
            field=models.ImageField(blank=True, upload_to='pic_folder/', verbose_name='Cargar imagen'),
        ),
    ]
