# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_auto_20170324_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='Colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='people.Colaborador'),
        ),
    ]
