# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_auto_20170326_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='img_issue',
            field=models.ImageField(blank=True, null=True, upload_to='img_preguntas', verbose_name='Cargar imagen'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='descripcion_img',
            field=models.ImageField(blank=True, null=True, upload_to='img_respuestas', verbose_name='Cargar imagen'),
        ),
    ]
