# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 23:41
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_auto_20170411_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='descripcion',
            field=tinymce.models.HTMLField(),
        ),
    ]
