# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_auto_20170412_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='slug',
        ),
    ]
