# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 22:24
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_remove_respuesta_descripcion_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='descripcion',
            field=tinymce.models.HTMLField(),
        ),
    ]
