# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 01:36
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170413_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='contenido'),
        ),
    ]
