# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170507_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Url de la nota', max_length=63, unique=True, verbose_name='url'),
        ),
    ]
