# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-08 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170507_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Url de la nota', max_length=63, unique_for_month='pub_date', verbose_name='url'),
        ),
    ]
