# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='es_docente',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='es_estudiante',
            field=models.BooleanField(default=True),
        ),
    ]
