# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-31 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20170320_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='link_facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='link_twitter',
            field=models.URLField(blank=True),
        ),
    ]
