# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_colaborador_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotoscolaboradores/'),
        ),
    ]
