# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20170404_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='foto',
            field=models.ImageField(blank=True, default='fotoscolaboradores/profile.jpg', null=True, upload_to='fotoscolaboradores'),
        ),
    ]
