# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20170411_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='es_docente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='link_facebook',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='link_twitter',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
