# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20170411_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='apellidos',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
