# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0011_auto_20170411_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='slug',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
