# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_auto_20170426_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='biografia',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
