# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_colaborador_biografia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='biografia',
        ),
    ]
